### PR TITLE
Simple approach for a docker container

### PR DESCRIPTION
**Pull request by thotmx**

### CODE REVIEW

**Comment by neomatrixcode** [comment]
I see it good.

**Comment by neomatrixcode** [comment]
Could you add the command to just build the image? I don't think that using docker compose is something very necessary.
Something like.

```
create the image:
docker build -t coding .

Use the image:
docker run --rm -it coding bash
```

**Comment by neomatrixcode** [comment]
Also, how feasible would it be to have an oaxacarb or oaxacoders account at dockerhub? 
So, you could upload an image like this and just give the user a single command to use.

`docker run --rm -it oaxacarb/coding bash`

**Comment by thotmx** [comment]
@neomatrixcode Yes, I used because my goal was generating a stack for rails, using a postgres container, and so on. But at the end I decided to use only the basic container. To build the complete stack step by step. And maybe use that for a workshop or something similar.

We have now a dockerhub account: https://hub.docker.com/u/oaxacarb

So, we can create it! Good idea!

**Review by JuanVqz — APPROVED** [review]

**Comment by JuanVqz** [comment]
I agree, at this point, we don't need `docker compose` but let's keep it, we can update the README or code in the following PRs.

**Pull request merged**
